"use client";

import { Activity, AlertTriangle, BrainCircuit, CircleGauge, Dna, RefreshCw, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { PageHeader } from "@/components/page-header";
import { api } from "@/lib/api";
import type { CognitiveTwin, Genome, MemoryHealth } from "@/types";

export default function IntelligencePage(){
  const [twin,setTwin]=useState<CognitiveTwin>();const [genome,setGenome]=useState<Genome>();const [health,setHealth]=useState<MemoryHealth>();const [busy,setBusy]=useState(false);
  const load=async()=>{setBusy(true);try{const [a,b,c]=await Promise.all([api.cognitiveTwin(),api.genome(),api.memoryHealth()]);setTwin(a);setGenome(b);setHealth(c);}finally{setBusy(false);}};
  useEffect(()=>{void Promise.all([api.cognitiveTwin(),api.genome(),api.memoryHealth()]).then(([a,b,c])=>{setTwin(a);setGenome(b);setHealth(c);});},[]);
  return <><PageHeader eyebrow="Self model" title="Intelligence Dashboard" description="Measure what you know, where confidence is weak, and whether your memory system can be trusted." action={<button onClick={()=>void load()} className="flex items-center gap-2 rounded-xl border hairline px-3 py-2 text-sm text-cyan"><RefreshCw size={14} className={busy?"animate-spin":""}/> Recalculate</button>}/>
    <div className="space-y-6 p-8">
      <div className="grid gap-4 md:grid-cols-3"><section className="hud-panel rounded-2xl p-5"><div className="flex items-center gap-2"><BrainCircuit size={16} className="text-cyan"/><span className="hud-label">Cognitive evidence</span></div><div className="data-value mt-5 text-4xl font-light">{twin?.knowledge_count??0}</div><p className="mt-1 text-xs text-muted">durable knowledge nodes</p></section><section className="hud-panel rounded-2xl p-5"><div className="flex items-center gap-2"><CircleGauge size={16} className="text-cyan"/><span className="hud-label">Mean confidence</span></div><div className="data-value mt-5 text-4xl font-light">{twin?.confidence??0}<span className="text-sm text-cyan">%</span></div><div className="progress-track mt-3"><div className="progress-fill" style={{width:`${twin?.confidence??0}%`}}/></div></section><section className="hud-panel rounded-2xl p-5"><div className="flex items-center gap-2"><ShieldCheck size={16} className="text-mint"/><span className="hud-label">Memory health</span></div><div className="data-value mt-5 text-4xl font-light">{health?.score??0}<span className="text-sm text-mint">/100</span></div><p className="mt-1 text-xs text-muted">{health?.issues.length??0} issues across {health?.scanned??0} memories</p></section></div>
      <section className="hud-panel rounded-2xl p-6"><div className="flex items-center gap-3"><Activity size={18} className="text-cyan"/><div><div className="hud-label">Cognitive twin</div><h2 className="mt-2 text-lg text-white">Current learning signal</h2></div></div><p className="mt-5 border-l border-cyan/30 pl-4 text-sm leading-7 text-slate-200">{twin?.insight??"Building your cognitive model..."}</p><div className="mt-6 grid gap-6 md:grid-cols-3"><div><h3 className="hud-label">Strongest domains</h3><div className="mt-3 space-y-2">{twin?.strongest_domains.map(([name,count])=><div key={name} className="flex items-center justify-between text-xs"><span className="text-slate-300">{name}</span><span className="text-cyan">{count}</span></div>)}</div></div><div><h3 className="hud-label">Memory composition</h3><div className="mt-3 space-y-2">{twin?.dominant_memory_types.map(([name,count])=><div key={name} className="flex items-center justify-between text-xs"><span className="capitalize text-slate-300">{name}</span><span className="text-cyan">{count}</span></div>)}</div></div><div><h3 className="hud-label">Learning profile</h3><div className="mt-3 space-y-2 text-xs text-slate-300"><div className="flex justify-between"><span>Explanation</span><span className="text-cyan">{twin?.preferences.explanation_style}</span></div><div className="flex justify-between"><span>Challenge</span><span className="text-cyan">{twin?.preferences.challenge_level}</span></div><div className="flex justify-between"><span>Session</span><span className="text-cyan">{twin?.preferences.session_minutes} min</span></div></div></div></div></section>
      <div className="grid gap-6 xl:grid-cols-[1fr_1fr]">
        <section className="hud-panel rounded-2xl p-6"><div className="flex items-center gap-2"><Dna size={18} className="text-cyan"/><div><div className="hud-label">Knowledge genome</div><h2 className="mt-2 text-lg text-white">Concept clusters</h2></div></div><div className="mt-5 flex flex-wrap gap-2">{genome?.concepts.map(concept=><div key={concept.name} title={`${concept.evidence} evidence nodes · ${concept.confidence}% confidence`} className="rounded-full border border-cyan/15 bg-cyan/[.04] px-3 py-2 text-xs text-slate-200"><span className="text-cyan">{concept.name}</span><span className="ml-2 text-muted">{concept.evidence}</span></div>)}{!genome?.concepts.length&&<p className="py-8 text-sm text-muted">Tag and categorize memories to reveal concept clusters.</p>}</div><div className="mt-6 border-t hairline pt-5"><div className="flex justify-between text-xs text-muted"><span>{genome?.goals.length??0} curriculum paths</span><span>{genome?.nodes.filter(node=>node.status==="mastered").length??0}/{genome?.nodes.length??0} nodes mastered</span></div></div></section>
        <section className="hud-panel rounded-2xl p-6"><div className="flex items-center gap-2"><AlertTriangle size={18} className="text-amber-300"/><div><div className="hud-label">Memory health</div><h2 className="mt-2 text-lg text-white">Integrity findings</h2></div></div><div className="mt-5 grid grid-cols-4 gap-2">{["duplicate","conflict","outdated","uncertain"].map(kind=><div key={kind} className="rounded-xl border hairline bg-black/15 p-3 text-center"><strong className="data-value block text-lg text-white">{health?.counts[kind]??0}</strong><span className="text-[9px] uppercase tracking-wider text-muted">{kind}</span></div>)}</div><div className="mt-4 max-h-72 space-y-2 overflow-y-auto">{health?.issues.map((issue,index)=><article key={`${issue.kind}-${issue.memory.id}-${index}`} className="rounded-xl border hairline bg-black/15 p-3"><div className="flex items-center justify-between"><span className="text-[9px] uppercase tracking-wider text-amber-200">{issue.kind}</span><span className="text-[10px] text-muted">{issue.reason}</span></div><h3 className="mt-2 text-xs text-white">{issue.memory.title}</h3><p className="mt-1 line-clamp-2 text-[11px] leading-5 text-muted">{issue.memory.fact}</p>{issue.related&&<p className="mt-2 border-l border-amber-300/20 pl-2 text-[10px] text-amber-100/70">Compared with: {issue.related.fact}</p>}</article>)}{!health?.issues.length&&<div className="py-10 text-center text-sm text-mint">No integrity problems detected.</div>}</div></section>
      </div>
    </div>
  </>;
}
