"use client";

import { ArrowLeft, BrainCircuit, CheckCircle2, FolderKanban, MessageSquare, Plus, Radar, Save, Target, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { PageHeader } from "@/components/page-header";
import { api } from "@/lib/api";
import type { ChatResponse, Project, ProjectDetail } from "@/types";

export default function ProjectsPage() {
  const [projects,setProjects]=useState<Project[]>([]);const [selected,setSelected]=useState<ProjectDetail|null>(null);
  const [name,setName]=useState("");const [description,setDescription]=useState("");const [note,setNote]=useState("");const [question,setQuestion]=useState("");const [answer,setAnswer]=useState<ChatResponse>();
  const [editName,setEditName]=useState("");const [editDescription,setEditDescription]=useState("");const [editGoal,setEditGoal]=useState("");const [editColor,setEditColor]=useState("#68e8ff");const [editStatus,setEditStatus]=useState<"active"|"paused"|"completed"|"archived">("active");
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const load=()=>api.projects().then(setProjects);
  useEffect(()=>{void load();},[]);
  const open=async(id:string)=>{setError("");setAnswer(undefined);try{const project=await api.project(id);setSelected(project);setEditName(project.name);setEditDescription(project.description);setEditGoal(project.goal);setEditColor(project.color);setEditStatus(project.status);}catch(reason){setError(reason instanceof Error?reason.message:"Could not open project");}};
  const refresh=async()=>{if(selected)setSelected(await api.project(selected.id));await load();};
  const create=async(event:FormEvent)=>{event.preventDefault();if(!name.trim())return;try{const project=await api.createProject(name.trim(),description.trim());setName("");setDescription("");await load();await open(project.id);}catch(reason){setError(reason instanceof Error?reason.message:"Could not create project");}};
  const save=async(event:FormEvent)=>{event.preventDefault();if(!selected)return;const project=await api.updateProject(selected.id,{name:editName.trim(),description:editDescription.trim(),goal:editGoal.trim(),color:editColor,status:editStatus});setSelected(project);await load();};
  const remove=async()=>{if(!selected||!confirm(`Delete project "${selected.name}"? Memories and chats will remain unassigned.`))return;await api.deleteProject(selected.id);setSelected(null);await load();};
  const addMemory=async(event:FormEvent)=>{event.preventDefault();if(!selected||!note.trim())return;await api.createMemory(note.trim(),selected.id);setNote("");await refresh();};
  const ask=async(event:FormEvent)=>{event.preventDefault();if(!selected||!question.trim())return;setBusy(true);try{setAnswer(await api.chat(question.trim(),undefined,"text",selected.id));}finally{setBusy(false);}};
  return <><PageHeader eyebrow="Mission control" title="Project Cockpit" description="Unify goals, evidence, next actions, decisions, and resurfaced knowledge around an outcome."/>
    <div className="p-8">{error&&<div className="mb-5 rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-200">{error}</div>}
      {!selected?<div className="grid gap-6 xl:grid-cols-[360px_1fr]"><div className="space-y-5"><form onSubmit={create} className="hud-panel rounded-2xl p-5"><div className="flex items-center gap-2"><Target size={17} className="text-cyan"/><h2 className="text-sm text-white">Create a mission</h2></div><input value={name} onChange={event=>setName(event.target.value)} placeholder="Project name" className="focus-ring mt-4 w-full rounded-xl border hairline bg-black/20 p-3 text-sm"/><textarea value={description} onChange={event=>setDescription(event.target.value)} placeholder="What outcome are you pursuing?" rows={5} className="focus-ring mt-3 w-full resize-none rounded-xl border hairline bg-black/20 p-3 text-sm"/><button className="mt-3 flex items-center gap-2 rounded-xl bg-cyan px-4 py-2 text-sm text-void"><Plus size={15}/> Create cockpit</button></form><div className="rounded-2xl border hairline bg-cyan/[.025] p-5"><h3 className="text-sm text-cyan">Why projects matter</h3><p className="mt-2 text-xs leading-6 text-muted">A cockpit narrows retrieval to one mission, measures execution, and resurfaces knowledge before it becomes forgotten.</p></div></div><div className="grid content-start gap-4 md:grid-cols-2">{projects.map(project=><button type="button" onClick={()=>void open(project.id)} key={project.id} className="hud-panel rounded-2xl p-5 text-left transition hover:border-cyan/35"><div className="flex items-center justify-between"><span className="block h-1.5 w-10 rounded-full" style={{background:project.color}}/><span className="text-[9px] uppercase tracking-wider text-muted">{project.status}</span></div><div className="mt-4 flex items-center gap-2"><FolderKanban size={17} className="text-cyan"/><h2 className="text-white">{project.name}</h2></div><p className="mt-2 min-h-10 text-sm text-muted">{project.description||"No mission statement yet."}</p><div className="progress-track mt-5"><div className="progress-fill" style={{width:`${project.progress}%`}}/></div><div className="mt-2 flex justify-between text-[10px] text-muted"><span>{project.memory_count} memories · {project.task_count} active tasks</span><span className="text-cyan">{project.progress}%</span></div></button>)}{!projects.length&&<div className="col-span-full grid min-h-52 place-items-center rounded-2xl border border-dashed hairline text-sm text-muted">Create the first project cockpit.</div>}</div></div>
      :<div className="space-y-5"><button onClick={()=>setSelected(null)} className="flex items-center gap-2 text-sm text-muted hover:text-white"><ArrowLeft size={16}/> All projects</button>
        <section className="hud-panel rounded-2xl p-6"><div className="flex flex-wrap items-start gap-4"><span className="mt-1 h-3 w-3 rounded-full" style={{background:selected.color}}/><div className="min-w-0 flex-1"><div className="flex items-center gap-3"><h2 className="text-xl text-white">{selected.name}</h2><span className="rounded-full border border-cyan/20 px-2 py-1 text-[9px] uppercase tracking-wider text-cyan">{selected.status}</span></div><p className="mt-1 text-sm text-muted">{selected.description||"No description yet."}</p>{selected.goal&&<p className="mt-3 border-l border-cyan/30 pl-3 text-xs leading-5 text-slate-300"><span className="text-cyan">Mission:</span> {selected.goal}</p>}</div><div className="flex gap-5 text-center"><div><strong className="data-value block text-lg text-cyan">{selected.memory_count}</strong><span className="text-[9px] uppercase tracking-wider text-muted">Memory</span></div><div><strong className="data-value block text-lg text-cyan">{selected.task_count}</strong><span className="text-[9px] uppercase tracking-wider text-muted">Active</span></div><div><strong className="data-value block text-lg text-mint">{selected.progress}%</strong><span className="text-[9px] uppercase tracking-wider text-muted">Complete</span></div></div></div><div className="progress-track mt-5"><div className="progress-fill" style={{width:`${selected.progress}%`}}/></div></section>
        <div className="grid gap-5 xl:grid-cols-2"><form onSubmit={ask} className="hud-panel rounded-2xl p-5"><div className="flex items-center gap-2 text-sm text-white"><MessageSquare size={17} className="text-cyan"/> Ask this project</div><p className="mt-2 text-xs text-muted">Source-backed answers are restricted to this project&apos;s current memory.</p><textarea value={question} onChange={event=>setQuestion(event.target.value)} rows={3} placeholder={`Ask about ${selected.name}...`} className="focus-ring mt-4 w-full resize-none rounded-xl border hairline bg-black/20 p-3 text-sm"/><button disabled={busy||!question.trim()} className="mt-3 rounded-xl bg-cyan px-4 py-2 text-sm text-void disabled:opacity-40">{busy?"Searching...":"Ask project"}</button>{answer&&<div className="mt-4 border-t hairline pt-4"><div className="prose prose-invert prose-sm text-sm leading-6 text-slate-200"><ReactMarkdown remarkPlugins={[remarkGfm]}>{answer.answer}</ReactMarkdown></div><div className="mt-3 flex flex-wrap gap-2">{answer.citations.map(citation=><span key={citation.id} title={citation.excerpt} className="rounded-full border hairline px-2 py-1 text-[9px] text-cyan">{citation.label}</span>)}</div></div>}</form><form onSubmit={addMemory} className="hud-panel rounded-2xl p-5"><div className="flex items-center gap-2 text-sm text-white"><BrainCircuit size={17} className="text-cyan"/> Add project memory</div><p className="mt-2 text-xs text-muted">This evidence becomes searchable only within the project when using project-scoped questions.</p><textarea value={note} onChange={event=>setNote(event.target.value)} rows={3} placeholder="Decision, fact, lesson, constraint..." className="focus-ring mt-4 w-full resize-none rounded-xl border hairline bg-black/20 p-3 text-sm"/><button disabled={!note.trim()} className="mt-3 flex items-center gap-2 rounded-xl bg-cyan px-4 py-2 text-sm text-void disabled:opacity-40"><Plus size={15}/> Save evidence</button></form></div>
        <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-5"><section className="hud-panel rounded-2xl p-5"><div className="flex items-center gap-2"><Radar size={17} className="text-cyan"/><h3 className="text-sm text-white">Smart resurfacing</h3></div><p className="mt-2 text-xs text-muted">High-value, uncertain, and long-unvisited project knowledge.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{selected.resurfaced.map(memory=><article key={memory.id} className="rounded-xl border border-cyan/15 bg-cyan/[.025] p-3"><div className="flex justify-between gap-2"><span className="text-[10px] text-cyan">{memory.reason}</span><span className="data-value text-[10px] text-muted">{Math.round(memory.resurface_score*100)}</span></div><h4 className="mt-2 text-xs text-white">{memory.title}</h4><p className="mt-1 line-clamp-3 text-[11px] leading-5 text-muted">{memory.normalized_fact}</p></article>)}{!selected.resurfaced.length&&<p className="col-span-full py-6 text-center text-xs text-muted">Add project memories to activate resurfacing.</p>}</div></section><section className="hud-panel rounded-2xl p-5"><h3 className="text-sm text-white">Knowledge base</h3><div className="mt-4 space-y-3">{selected.memories.map(memory=><article key={memory.id} className="rounded-xl border hairline bg-black/15 p-3"><div className="flex items-center gap-2"><span className="rounded-full bg-cyan/5 px-2 py-1 text-[9px] uppercase text-cyan">{memory.memory_type}</span><span className="text-sm text-white">{memory.title}</span></div><p className="mt-2 text-xs leading-5 text-muted">{memory.normalized_fact}</p></article>)}{!selected.memories.length&&<p className="py-8 text-center text-sm text-muted">No memories yet.</p>}</div></section><section className="hud-panel rounded-2xl p-5"><h3 className="text-sm text-white">Execution snapshot</h3><div className="mt-4 space-y-2">{selected.tasks.slice(0,8).map(task=><div key={task.id} className="flex items-center gap-3 rounded-xl border hairline p-3"><CheckCircle2 size={14} className={task.status==="done"?"text-mint":"text-muted"}/><span className="flex-1 text-xs text-slate-200">{task.title}</span><span className="text-[9px] uppercase text-muted">{task.status.replace("_"," ")}</span></div>)}</div></section></div>
          <form onSubmit={save} className="hud-panel h-fit rounded-2xl p-5"><h3 className="text-sm text-white">Cockpit settings</h3><label className="mt-4 block text-xs text-muted">Name</label><input value={editName} onChange={event=>setEditName(event.target.value)} className="mt-2 w-full rounded-xl border hairline bg-black/20 p-3 text-sm"/><label className="mt-4 block text-xs text-muted">Mission / measurable outcome</label><textarea value={editGoal} onChange={event=>setEditGoal(event.target.value)} rows={3} className="mt-2 w-full resize-none rounded-xl border hairline bg-black/20 p-3 text-sm"/><label className="mt-4 block text-xs text-muted">Description</label><textarea value={editDescription} onChange={event=>setEditDescription(event.target.value)} rows={3} className="mt-2 w-full resize-none rounded-xl border hairline bg-black/20 p-3 text-sm"/><label className="mt-4 block text-xs text-muted">Status</label><select value={editStatus} onChange={event=>setEditStatus(event.target.value as typeof editStatus)} className="mt-2 w-full rounded-xl border hairline bg-panel p-3 text-sm"><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option><option value="archived">Archived</option></select><label className="mt-4 block text-xs text-muted">Color</label><input type="color" value={editColor} onChange={event=>setEditColor(event.target.value)} className="mt-2 h-10 w-full rounded-lg border hairline bg-transparent"/><div className="mt-5 flex gap-2"><button className="flex items-center gap-2 rounded-xl bg-cyan px-3 py-2 text-xs text-void"><Save size={14}/> Save</button><button type="button" onClick={()=>void remove()} className="ml-auto flex items-center gap-2 rounded-xl border border-red-400/20 px-3 py-2 text-xs text-red-200"><Trash2 size={14}/> Delete</button></div></form></div>
      </div>}
    </div>
  </>;
}
